// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9jhpgKlBXMX942QZFgwMeDwHdhabJlA',
    appId: '1:190120307124:web:8db993bc22c4af1478aae1',
    messagingSenderId: '190120307124',
    projectId: 'labactivitymarch27',
    authDomain: 'labactivitymarch27.firebaseapp.com',
    storageBucket: 'labactivitymarch27.appspot.com',
    measurementId: 'G-BKQJX6T0NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzc1sJT7DmayPKjuDtYvjzH0lcYxXXVA',
    appId: '1:190120307124:android:0ab37e0af824931678aae1',
    messagingSenderId: '190120307124',
    projectId: 'labactivitymarch27',
    storageBucket: 'labactivitymarch27.appspot.com',
  );
}
